#ifndef INCLUDE_STADO_VECTOR_NATIVE_OPERATIONS_HPP
#define INCLUDE_STADO_VECTOR_NATIVE_OPERATIONS_HPP

// IWYU pragma: begin_exports
#include "operations/128f.hpp"
#include "operations/128i.hpp"
#include "operations/256f.hpp"
#include "operations/256i.hpp"
#include "operations/512bw.hpp"
#include "operations/512f.hpp"
#include "operations/512i.hpp"
#include "operations/f32x04.hpp"
#include "operations/f32x08.hpp"
#include "operations/f32x16.hpp"
#include "operations/f64x02.hpp"
#include "operations/f64x04.hpp"
#include "operations/f64x08.hpp"
#include "operations/i08x16.hpp"
#include "operations/i08x32.hpp"
#include "operations/i08x64.hpp"
#include "operations/i16x08.hpp"
#include "operations/i16x16.hpp"
#include "operations/i16x32.hpp"
#include "operations/i32x04.hpp"
#include "operations/i32x08.hpp"
#include "operations/i32x16.hpp"
#include "operations/i64x02.hpp"
#include "operations/i64x04.hpp"
#include "operations/i64x08.hpp"
#include "operations/u08x16.hpp"
#include "operations/u08x32.hpp"
#include "operations/u08x64.hpp"
#include "operations/u16x08.hpp"
#include "operations/u16x16.hpp"
#include "operations/u16x32.hpp"
#include "operations/u32x04.hpp"
#include "operations/u32x08.hpp"
#include "operations/u32x16.hpp"
#include "operations/u64x02.hpp"
#include "operations/u64x04.hpp"
#include "operations/u64x08.hpp"
// IWYU pragma: end_exports

#endif // INCLUDE_STADO_VECTOR_NATIVE_OPERATIONS_HPP
